name: Java CI Pipeline

on:
  push:
    branches: [ ci/lea/github-actions ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        run: mvn clean test

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Integration Tests
        run: mvn verify -Pintegration-test

 
  generate-docs:
  name: Generate Documentation
  runs-on: ubuntu-latest
  needs: [unit-test, integration-test]
  if: contains(github.event.head_commit.modified_files, 'ci/lea/github-actions') || 
      contains(github.event.head_commit.added_files, 'ci/lea/github-actions') ||
      contains(github.event.head_commit.removed_files, 'ci/lea/github-actions')
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate Javadoc
      run: mvn javadoc:javadoc

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: project-documentation
        path: target/site/apidocs

